name: GitFlow Workflow

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - main
      - release/*
      - hotfix/*

env:
  WORKFLOW_VERSION: 1.0.0
  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  JIRA_USERNAME: ${{ vars.JIRA_USERNAME }}
  JIRA_DOMAIN: ${{ vars.JIRA_DOMAIN }}
  LLM_TOKEN: ${{ secrets.LLM_TOKEN }}
  PARENT_PAGE_ID: 5931009
jobs:
  initialize:
    uses: VirdocsSoftware/github-actions/.github/workflows/initialize.yml@ar-CORE-1467-create-sharable-jobs
    permissions:
      actions: write
      contents: read
    secrets:
      env-github-token: ${{ secrets.GITHUB_TOKEN }}
  unit-tests:
    name: Unit Tests
    needs: [initialize]
    if: |
      ! ( github.event_name == 'push' &&
      github.ref == 'refs/heads/main' )
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

  feature-tests:
    name: Feature Tests
    needs: [initialize]
    runs-on: ubuntu-latest
    if: |
      ! ( github.event_name == 'push' &&
      github.ref == 'refs/heads/main' )
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

  deploy-check:
    name: Deployment Check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: |
      ! contains(github.event.pull_request.body, '[x] Skip CD')
    steps:
      - name: Announce Deployment
        run: echo "This will be deployed"

  check-release:
    name: Check Release
    timeout-minutes: 5
    if: |
      startsWith(github.head_ref,'release/v') || startsWith(github.head_ref,'hotfix/v') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: VirdocsSoftware/github-actions/.github/actions/check-release@ar-CORE-1467-create-sharable-jobs
    permissions:
      contents: read
    with:
      head-ref: ${{ github.head_ref }}
      base-ref: ${{ github.base_ref }}
      event-name: ${{ github.event_name }}

  semantic-pre-release:
    name: Semantic Pre Release
    needs: [deploy-check, unit-tests, feature-tests, initialize]
    timeout-minutes: 15
    permissions:
      contents: write
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/develop'
    uses: VirdocsSoftware/github-actions/.github/actions/semantic-pre-release@ar-CORE-1467-create-sharable-jobs
    with:
      semantic-github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-develop:
    name: Deploy to Develop
    needs: [deploy-check, unit-tests, feature-tests, initialize]
    environment: develop
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4

  integration-testing:
    name: Integration Testing
    needs: [deploy-to-develop, initialize]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

  deploy-to-staging:
    name: Deploy to Staging
    needs: [deploy-check, unit-tests, feature-tests, check-release, initialize]
    environment: staging
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      github.event_name == 'pull_request' && github.base_ref == 'main' &&
      (startsWith(github.head_ref, 'release/v') || startsWith(github.head_ref, 'hotfix/v'))
    steps:
      - uses: actions/checkout@v4

  tag-jira-release:
    needs: [deploy-to-develop]
    uses: VirdocsSoftware/github-actions/.github/actions/tag-tickets-with-release@ar-CORE-1467-create-sharable-jobs
    with:
      target-branch: 'origin/main'
      jira-domain: ${{ env.JIRA_DOMAIN }}
      jira-username: ${{ env.JIRA_USERNAME }}
    secrets:
      jira-api-token: ${{ env.JIRA_API_TOKEN }}
      llm-token: ${{ env.LLM_TOKEN }}
      

  tag-jira-relesae-or-hotfix:
    runs-on: ubuntu-latest
    needs: [deploy-to-staging]
    uses: VirdocsSoftware/github-actions/.github/actions/tag-tickets-with-release@ar-CORE-1467-create-sharable-jobs
    with:
      target-branch: 'origin/main'
      jira-domain: ${{ env.JIRA_DOMAIN }}
      jira-username: ${{ env.JIRA_USERNAME }}
      is-release: true
    secrets:
      jira-api-token: ${{ env.JIRA_API_TOKEN }}
      llm-token: ${{ env.LLM_TOKEN }}

  deploy-to-production:
    name: Deploy to Production
    needs: [deploy-check, check-release, initialize]
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

  semantic-release:
    name: Semantic Release
    timeout-minutes: 15
    permissions:
      contents: write
    needs: [deploy-to-production]
    uses: VirdocsSoftware/github-actions/.github/actions/semantic-release@ar-CORE-1467-create-sharable-jobs
    with:
      semantic-github-token: ${{ secrets.GITHUB_TOKEN }}

  notify-release:
    name: Notify Release
    needs: [deploy-to-production, semantic-release]
    uses: VirdocsSoftware/github-actions/.github/actions/release-notes@ar-CORE-1467-create-sharable-jobs
    with:
      version: ${{ needs.semantic-release.outputs.new-tag }}
      parent-page-id: ${{ env.PARENT_PAGE_ID }}
      jira-username: ${{ env.JIRA_USERNAME }}
      jira-domain: ${{ env.JIRA_DOMAIN }}
    secrets:
      jira-api-token: ${{ env.JIRA_API_TOKEN }}